# Day 2

# Loops

In [1]:
# While Loop

In [2]:
x=1
while x < 6:
    print(x)
    x = x + 1

1
2
3
4
5


In [3]:
x=1
while x< 6:
    print(x)
    x=x+1

1
2
3
4
5


In [6]:
x=1
while x<8:
    print('x is',x)
    x += 1
else:
    print('x is no longer < 8')

x is 1
x is 2
x is 3
x is 4
x is 5
x is 6
x is 7
x is no longer < 8


In [12]:
T=15
while T<70:
    F=((9*T)/5)+32
    print(T,F)
    T += 5

15 59.0
20 68.0
25 77.0
30 86.0
35 95.0
40 104.0
45 113.0
50 122.0
55 131.0
60 140.0
65 149.0


In [13]:
D=5
while D<=80:
    Y=(273+D)
    print(D,Y)
    D += 5

5 278
10 283
15 288
20 293
25 298
30 303
35 308
40 313
45 318
50 323
55 328
60 333
65 338
70 343
75 348
80 353


In [16]:
G=5
while G<=80:
    R=(273+G)
    print(G,R)
    G += 5

5 278
10 283
15 288
20 293
25 298
30 303
35 308
40 313
45 318
50 323
55 328
60 333
65 338
70 343
75 348
80 353


# For Loop

In [20]:
# Example with string
Language = 'PYTHON PROGRAMMING'
for l in Language:
    print(l)

P
Y
T
H
O
N
 
P
R
O
G
R
A
M
M
I
N
G


In [21]:
Interns = ['chris','james','desmond','jannatt']
for d in Interns:
    print(d)

chris
james
desmond
jannatt


In [23]:
for x in range (1,25,3):
    print(x)

1
4
7
10
13
16
19
22


In [25]:
for x in range (1,36):
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35


In [26]:
import numpy as np

In [29]:
days= np.arange(1,367)
days

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
       170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 18

In [32]:
import numpy as dy
days= dy.arange(1,101)
for x in range(1,100,2):
    print(x)

1
3
5
7
9
11
13
15
17
19
21
23
25
27
29
31
33
35
37
39
41
43
45
47
49
51
53
55
57
59
61
63
65
67
69
71
73
75
77
79
81
83
85
87
89
91
93
95
97
99


In [34]:
days = dy.arange(1,101,2)
days

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [36]:
import numpy as rt
days= rt.arange(1,101)
for x in range(1,101,3):
    print(x)

1
4
7
10
13
16
19
22
25
28
31
34
37
40
43
46
49
52
55
58
61
64
67
70
73
76
79
82
85
88
91
94
97
100


In [39]:
days= rt.arange(1,101,3)
days

array([  1,   4,   7,  10,  13,  16,  19,  22,  25,  28,  31,  34,  37,
        40,  43,  46,  49,  52,  55,  58,  61,  64,  67,  70,  73,  76,
        79,  82,  85,  88,  91,  94,  97, 100])

# Nested For Loop

In [41]:
A = [1,2,3,4,5,6,7,8,9,10]
B = [5]
for a in A:
    for b in B:
        y = a * b
        print(b,'*',a,'=',y)

5 * 1 = 5
5 * 2 = 10
5 * 3 = 15
5 * 4 = 20
5 * 5 = 25
5 * 6 = 30
5 * 7 = 35
5 * 8 = 40
5 * 9 = 45
5 * 10 = 50


In [42]:
G = [1,2,3,4,5,6,7,8,9,10,11,12]
F = [5]
for g in G:
    for f in F:
        w = g * f
        print(f,'*',g,'=',w)

5 * 1 = 5
5 * 2 = 10
5 * 3 = 15
5 * 4 = 20
5 * 5 = 25
5 * 6 = 30
5 * 7 = 35
5 * 8 = 40
5 * 9 = 45
5 * 10 = 50
5 * 11 = 55
5 * 12 = 60


In [45]:
N = [2,4]
M = [3,5]
O = [1,2]
for n in N:
    for m in M:
        for o in O:
            u = n + m + o
            print(n,'+',m,'+',o,'=',u)
    

2 + 3 + 1 = 6
2 + 3 + 2 = 7
2 + 5 + 1 = 8
2 + 5 + 2 = 9
4 + 3 + 1 = 8
4 + 3 + 2 = 9
4 + 5 + 1 = 10
4 + 5 + 2 = 11


# LOOP CONTROL

# Break

In [51]:
names = ['john','gideon','prosper','mary']
for name in names:
    if name == 'john':
        print(name,"'found him'")
        break

john 'found him'


In [57]:
name= input('state your name')
for name in name:
    if name == 'john':
        print(name,"'welcome'")
else:
    print('intruder')
    

state your namejohn
intruder


# Continue

In [71]:
ctr = 0
for ctr in range(10):
    ctr = ctr + 1
    
    if ctr == 5:
        print('add + 1')
        
        continue
        print('This wont be printed too')
    print('Number is ' + str(ctr))
print('out of loop')

Number is 1
Number is 2
Number is 3
Number is 4
add + 1
Number is 6
Number is 7
Number is 8
Number is 9
Number is 10
out of loop


# Pass

In [72]:
X='kwame'
if x=='Ama':
    pass

In [75]:
numbers = [1,2,3,4,5,6,7,8,9,10]
for number in numbers:
    if number % 2 != 0:
        pass
    else:
        print('number is ',number)

number is  2
number is  4
number is  6
number is  8
number is  10


In [76]:
menu = {'salad': 'vitamin', 'potato': 'carbohydrate', 'chicken': 'protein', 'yoghurt':'mineral'}
while True:
    menu_choice = input('what would you like to have?: ')
    if menu_choice == 'none':
        break
    if menu_choice in menu:
        food = menu.get(menu_choice)
        print(food)
    else:
        print('we don\'nt have' + menu_choice)

what would you like to have?: salad
vitamin
what would you like to have?: none


# Functions

In [77]:
def welcome():
    c = 'Hello, welcome to PY4CA'
    return c

In [78]:
welcome()

'Hello, welcome to PY4CA'

In [79]:
def sum_of_numbers(a,b):
    c=a+b
    return c

In [83]:
# a and b are called dummy variables

In [80]:
sum_of_numbers(20,5)

25

In [84]:
def power(a,b):
    i=a**b
    return i
x = 2
y = 3
power(x,y)

8

In [82]:
power(2,2)

4

In [85]:
def name():
    chris = 'how may i help you'
    return chris

In [87]:
name()

'how may i help you'

In [97]:
def k(a):
    q=(a**2) +10
    return q

In [98]:
k(4)

26

In [99]:
k(5)

35

In [100]:
def potential_temperature(T,P0,P1):
    answer=T*(P0/P1)**0.286
    return answer

In [101]:
potential_temperature(50,120,111)

51.12737184220884

In [115]:
def p_temp(T,p0,p1):
    P = p0/p1
    expo = 0.286
    answer = T*P**expo
    return answer

In [116]:
p_temp(12 ,7 ,6)

12.54088045194079

In [121]:
def potential_temperature(T,P0,P1,units):
    if units.upper()=='C' or units.upper()=='CELSIUS':
        T=T+273.15
        answer=T*(P0/P1)**0.286
        answer=answer-273.15
    elif units.upper()=='K'or units.upper()=='KELVIN':
        answer=T*(P0/P1)**0.286
    return answer


In [131]:
potential_temperature(28,1000,750,'c')

53.82560059991221

In [133]:
def p_temp(T,p0,p1,units):
    P = p0/p1
    expo = 0.286
    if units.upper()=='C' or units.upper()=='CELSIUS':
        T=T+273.15
        answer=T*P**expo
        answer=answer-273.15
    elif units.upper()=='K' or units.upper()=='KELVIN':
        answer=T*P**expo
    return answer

In [134]:
p_temp(47,56,16,'c')

184.94649282813134

# Looping Within Functions

In [135]:
def test(x,max_x,x_interval):
    while(x<max_x):
        print(x)
        x+=x_interval
    return x

In [137]:
test(2,50,2)

2
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48


50

# Lambda Expressions

In [138]:
square = lambda x:x**2
square(10)

100

In [139]:
add = lambda d:d*5+6

In [140]:
add(67)

341